### ISSUE TITLE
Could not run Nuxt 3

### ISSUE THREAD

**Issue by lucpotage** [codesandbox/codesandbox-ios#26]
I created a new sandbox that works well on the web but on iPad, I was not able to build the project. I opened an issue in Nuxt repo but it does not seem related to Nuxt: https://github.com/nuxt/nuxt.js/issues/13913

Here is the error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /private/var/mobile/Containers/Data/Application/…/Documents/sandboxes/jgo3l1/src/node_modules/nuxt/bin/nuxt.mjs
at Module.load (internal/modules/cjs/loader.js:1007:11)
at Function.Module._load (internal/modules/cjs/loader.js:903:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
at MessagePort. (internal/main/worker_thread.js:167:24)
at MessagePort.emit (events.js:321:20)
at MessagePort.onmessage (internal/worker/io.js:78:8)
```

**Comment by tylerforesthauser** [comment]
@lucpotage Hey hey, did you ever get this working? Just tried to fire up a repo on my phone and ran into this issue…

**Comment by lucpotage** [comment]
I actually opened the CodeSandbox link in the Nuxt 3 documentation from iPad and it worked directly!
https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox
